version: '3.9'
services:
    db:
        image: postgres
        ports:
            - 127.0.0.1:5432:5432
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}